
def get_job_titles():
  return [
    "Developer",
    "Analyst",
    "Software Engineer",
    "Senior Developer",
    "Architect",
    "DevOps Engineer",
    "Project Manager",
    "Graduate",
    "Consultant",
    "Senior Software Engineer",
    "Software Developer",
    "Full Stack Developer",
    "Java Developer",
    "Data Engineer",
    "Business Analyst",
    ".NET Developer",
    "Front End Developer",
    "Designer",
    "Solutions Architect",
    "Senior Manager",
    "Product Manager",
    "Cloud Engineer",
    "Trainee",
    "IT Manager",
    "C# Developer",
    "Senior Analyst",
    "Support Engineer",
    "Infrastructure Engineer",
    "Java Engineer",
    "Support Analyst",
    "React Developer",
    "Data Analyst",
    "Administrator",
    "IT Support",
    "Lead Developer",
    "Product Owne",
    "Programmer",
    "Systems Engineer",
    "Network Engineer",
    "IT Analyst",
    "AWS Engineer",
    "Test Engineer",
    "Team Leader",
    "IT Engineer",
    "Backend Developer",
    "Python Developer",
    "Senior DevOps",
    "UX Designer",
    "Applications Support",
    "Service Analyst",
    "Principal Engineer",
    "QA Engineer",
    "Azure Engineer",
    "Technical Leader",
    "Senior Java Developer",
    "Senior DevOps Engineer",
    "PHP Developer",
    "Security Engineer",
    "Data Scientist",
    "Senior Data Engineer",
    "Python Engineer",
    "Delivery Manager",
    "C# .NET Developer",
    "Senior Project Manager",
    "Data Manager",
    "Tester",
    "Java Software Engineer",
    "Lead Software Engineer",
    "JavaScript Developer",
    "IT Project Manager",
    "Senior Software Developer",
    "Data Architect",
    "Technical Manager",
    "Service Manager",
    "Cloud Architect",
    "Senior Front-End Developer",
    "Senior Designer",
    "Web Developer",
    "Development Manager",
    "Senior .NET Developer",
    "IT Technician",
    "Security Analyst",
    "2nd Line Support",
    "Senior Full Stack Developer",
    "Statistical Programmer",
    "Service Desk Analyst",
    "Scrum Master",
    "Engineering Manager",
    "Developer/Software Engineer",
    "Embedded Engineer",
    "Applications Engineer",
    "Technical Support",
    "Senior Java Engineer",
    "UI Designer",
    "Graduate Software Engineer",
    "Coordinator",
    "Security Manager",
    "Technical Architect",
    "SQL Developer",
    "Software Manager",
    "Business Intelligence Developer",
    "Security Architect",
    ".NET Software Developer",
    "Junior Developer",
    "Technical Analyst",
    "Embedded Software Engineer",
    "Applications Developer",
    "Senior Architec",
    "Site Reliability Engineer",
    "Senior Programmer",
    "Senior Consultant",
    "Platform Engineer",
    "Android Developer",
    "Systems Analyst",
    "Senior Business Analyst",
    "Applications Support Analyst",
    "Test Analyst",
    "IT Support Engineer",
    "QA Leader",
    "AWS Developer",
    "iOS Developer",
    "Automation Engineer",
    "UI/UX Designer",
    "Angular Developer",
    "Financial Analyst",
    "Programme Manager",
    "Senior Product Manager",
    "Business Manager",
    "AWS DevOps",
    "Desktop Support",
    "Site Engineer",
    "Systems Administrator",
    "Azure Architect",
    "Network Technician",
    "Senior Data Scientist",
    "Python Software Engineer",
    "IT Support Analyst",
    "Trainee Technician",
    "1st Line Support",
    "C# Software Developer",
    "3rd Line Engineer",
    "JavaScript Engineer",
    "Security Consultant",
    "Trainee IT Technician",
    "Senior Cloud Engineer",
    "2nd Line Engineer",
    "Senior Statistical Programmer",
    "Trainee Developer",
    "AWS DevOps Enginee",
    "Business Intelligence Analyst",
    "Operations Manager",
    "Development Engineer",
    "Principal Software Engineer",
    "Trainee Software Developer",
    "Lead DevOps",
    ".NET Software Engineer",
    "Software Test Engineer",
    "Data Administrator",
    "Support Manager",
    "Node.js Developer",
    "Android Engineer",
    "Enterprise Architect",
    "Automation Tester",
    "Infrastructure Manager",
    "Senior Infrastructure Engineer",
    "Senior React Developer",
    "Azure Developer",
    "C++ Developer",
    "Technical Consultant",
    "Senior C# Developer",
    "Operations Engineer",
    "Linux Engineer",
    "Java Software Developer",
    "Digital Analyst",
    "C# Software Engineer",
    "AWS Software Engineer",
    "Azure DevOps Engineer",
    "GCP Engineer",
    "AWS Architect",
    "Lead Architect",
    "Graduate Developer",
    "Mobile Developer",
    "Senior UX Designer",
    "Principal Architect",
    "Test Automation Engineer",
    "Quality Engineer",
    "Information Analyst",
    "Product Analyst",
    "3rd Line Support",
    "C++ Software Engineer",
    "Salesforce Developer",
    "UI Developer",
    "Software Development Engineer",
    "Technical Engineer",
    "Service Delivery Manager",
    "Analytics Manager",
    "SQL Analyst",
    "Support Technician"
  ]